In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.linalg

In [14]:
# 6.1
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
B =np.array([12,2,1])

np.linalg.solve(A,B)

array([-9.2       ,  0.9       ,  6.46666667])

In [22]:
# 6.2
A2 = np.array([[1,2,-1],[3,-4,0],[8,-5,2],[2,0,-5],[11,4,-7]])
B2 = np.array([1,7,12,7,15])

np.linalg.lstsq(A2,B2,rcond = None)

(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [15]:
# 6.3 - на самом деле эта система решений не имеет
A3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
B3 = np.array([12,2,1])

np.linalg.solve(A3,B3)

array([ 2.83726777e+16, -5.67453553e+16,  2.83726777e+16])

In [16]:
# если поменять вектор B на (0,12,24) такая система будет иметь решение
# z = -1/3x-2/3y
# z = 4 - x - y
# показано на листочке

B3_1 =np.array([0,12,24])
np.linalg.solve(A3,B3_1)

array([-1., 14., -9.])

In [24]:
# 6.4
A4 = np.array([[1,2,3],[2,6,21],[4,28,73]])
P,L,U = scipy.linalg.lu(A4)
print(P)
print(L)
print(U)
B4 = np.array([-1,0,16])
np.linalg.solve(A4,B4)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.    0.    0.   ]
 [0.5   1.    0.   ]
 [0.25  0.625 1.   ]]
[[  4.      28.      73.    ]
 [  0.      -8.     -15.5   ]
 [  0.       0.      -5.5625]]


array([-3.,  1., -0.])

In [26]:
# 6.5
def Q(x,y,z):
    return np.sqrt(x**2 + y**2 + z**2)

A5 = np.array([[1,2,-1],[8,-5,2]])
B5 = np.array([1,12])

np.linalg.lstsq(A5,B5,rcond = None)

(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

In [23]:
# 6.6
A6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
B6 = np.array([2,5,11])

np.linalg.lstsq(A2,B2,rcond = None)

(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))